/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-26 13:27:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.*;
import models.Patient;

public final class patient_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(5);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("models.Patient");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Patient patient = (Patient) session.getAttribute("patient_signIn");
if (patient == null) {
	response.sendRedirect("patient/sign-in.jsp");
	return;
}
patient.generateNewCase();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Patient</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	background-color: #f4f4f4;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	max-width: 800px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table, th, td {\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("	background-color: #f2f2f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group {\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("	display: block;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"], input[type=\"password\"], input[type=\"email\"], input[type=\"tel\"]\r\n");
      out.write("	{\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"submit\"], button {\r\n");
      out.write("	background-color: #4CAF50;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	margin-right: 10px; /* Added margin for spacing */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"submit\"]:hover, button:hover {\r\n");
      out.write("	background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".action-button {\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".update-box {\r\n");
      out.write("	background-color: #e7f3fe;\r\n");
      out.write("	color: #31708f;\r\n");
      out.write("	border: 1px solid #bce8f1;\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".action-form {\r\n");
      out.write("	display: inline;\r\n");
      out.write("	margin-right: 10px; /* Added margin for spacing */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>Case number: </h1>\r\n");
      out.write("	<p>");
 out.print(patient.toString());  
      out.write("</p>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"patient_edit\" method=\"get\">\r\n");
      out.write("        <input type=\"submit\" name=\"cancelCase\" value=\"cancel case\">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"patient_edit\" method=\"get\">\r\n");
      out.write("	<label for=\"email\">Enter your email</label>\r\n");
      out.write("        <input type=\"email\" id=\"email\" name=\"email\"/>\r\n");
      out.write("        <input type=\"submit\" name=\"changeEmail\" value=\"Change email\">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"patient_edit\" method=\"get\">\r\n");
      out.write("	<label for=\"phoneNumber\">Enter your Phone Number</label>\r\n");
      out.write("        <input type=\"tel\" id=\"phoneNumber\" name=\"phoneNumber\"/>\r\n");
      out.write("        <input type=\"submit\" name=\"changeNumber\" value=\"Change phone number\">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"patient_edit\" method=\"get\">\r\n");
      out.write("	<label for=\"firstName\">First Name</label>\r\n");
      out.write("        <input type=\"text\" id=\"firstName\" name=\"firstName\"/>\r\n");
      out.write("        <input type=\"submit\" name=\"changeFirstName\" value=\"Change first name\">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"patient_edit\" method=\"get\">\r\n");
      out.write("	<label for=\"lastName\">Last Name</label>\r\n");
      out.write("        <input type=\"text\" id=\"lastName\" name=\"lastName\"/>\r\n");
      out.write("        <input type=\"submit\" name=\"changeLastName\" value=\"Change last name\">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"patient_edit\" method=\"get\">\r\n");
      out.write("	<label for=\"dob\">Date of Birth</label>\r\n");
      out.write("        <input type=\"date\" id=\"dob\" name=\"dob\" />\r\n");
      out.write("        <input type=\"submit\" name=\"changeDob\" value=\"Change dob\">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"patient_edit\" method=\"get\">\r\n");
      out.write("	<label for=\"medicalHistory\">Medical History</label>\r\n");
      out.write("	<textarea name=\"medicalHistory[]\" required></textarea>\r\n");
      out.write("        <input type=\"submit\" name=\"changeHistory\" value=\"Change history\">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"patient_edit\" method=\"get\">\r\n");
      out.write("	<label for=\"chronicDiseases\">Chronic Diseases</label>\r\n");
      out.write("	<textarea name=\"chronicDiseases[]\" required></textarea>\r\n");
      out.write("        <input type=\"submit\" name=\"changeChronic\" value=\"Change chronic\">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"patient_edit\" method=\"get\">\r\n");
      out.write("	<label for=\"allergies\">Allergies</label>\r\n");
      out.write("	<textarea name=\"allergies[]\" required></textarea>\r\n");
      out.write("        <input type=\"submit\" name=\"changeAllergy\" value=\"Change allergy\">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<form>\r\n");
      out.write("	<label>Check if you are submitting this case on behalf of someone else</label>\r\n");
      out.write("		<input type=\"checkbox\" name=\"sub_patient\" />\r\n");
      out.write("    <div id=\"patient-info\" class=\"hidden-section\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>Enter Patient Name</label>\r\n");
      out.write("        <input type=\"text\" name=\"sub_patient_name\"/>\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>Enter Patient Relation</label>\r\n");
      out.write("        <input type=\"text\" name=\"sub_patient_relation\"/>\r\n");
      out.write("        \r\n");
      out.write("        <br>\r\n");
      out.write("        <label for=\"symptoms\">symptoms</label>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div id=\"subsymptomscontainer\">\r\n");
      out.write("            <textarea name=\"symptoms[]\"></textarea>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <button type=\"button\" class=\"add-button\" onclick=\"addField('subsymptomscontainer', 'symptoms')\">Add Another symptom</button>\r\n");
      out.write("    <label>is the patient injured?</label>\r\n");
      out.write("    <input type=\"checkbox\" name=\"injured\" />  \r\n");
      out.write("    <div id=\"injury\" class=\"hidden-section\">\r\n");
      out.write("    	<br>\r\n");
      out.write("        <label>Enter injury</label>\r\n");
      out.write("        <input type=\"text\" name=\"injury_name\"/>\r\n");
      out.write("        <br>\r\n");
      out.write("        <label for=\"img\">injury image:</label>\r\n");
      out.write("  		<input type=\"file\" id=\"img\" name=\"img\" accept=\"image/*\">\r\n");
      out.write(" 	 	<br>\r\n");
      out.write("    </div> \r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("    <input type=\"submit\" name=\"changeSub\" value=\"change sub patient\" />\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
